apiVersion: apps/v1
kind: Deployment
metadata:   
  annotations:  
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas" 
  name: go-jhtbmyss
spec:
  replicas: 1 
  template: 
    spec:
      containers:
      - image: quay.io/rhtap_qe/go-jhtbmyss:14c6c6ae670dcd38285bdff99d3f5071a225b483@sha256:20e2055c1041f011e41c6a00c4cd0eb80a4d0d6031fce0ff45103548a55563b1
        name: container-image  
